<div class="accent-block">
	WIR LEISTEN HILFE NUR FÜR ONLINE-PRÜFUNGEN UND ONLINE-KLAUSUREN OHNE PROCTORING-SYSTEM (AUSWEISKONTROLLE, VIDEOÜBERWACHUNG). <br> BEI PRÄSENZKLAUSUREN KÖNNEN WIR KEINE UNTERSTÜTZUNG ANBIETEN.
</div>